# Generated by Django 5.1.6 on 2025-03-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='콘텐츠 ID')),
                ('type', models.CharField(choices=[('웹툰', '웹툰'), ('웹소설', '웹소설')], max_length=20, verbose_name='타입')),
                ('platform', models.CharField(choices=[('네이버웹툰', '네이버웹툰'), ('네이버시리즈', '네이버시리즈'), ('카카오웹툰', '카카오웹툰'), ('카카오페이지', '카카오페이지')], max_length=50, verbose_name='플랫폼')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('status', models.CharField(choices=[('연재', '연재'), ('완결', '완결'), ('휴재', '휴재')], max_length=20, verbose_name='연재 상태')),
                ('update_days', models.CharField(blank=True, max_length=37, null=True, verbose_name='연재 요일')),
                ('thumbnail', models.URLField(verbose_name='썸네일 URL')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('views', models.BigIntegerField(blank=True, null=True, verbose_name='조회수')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='평점')),
                ('likes', models.BigIntegerField(blank=True, null=True, verbose_name='좋아요 수')),
                ('synopsis', models.TextField(verbose_name='작품 소개')),
                ('keywords', models.TextField(verbose_name='키워드')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='작가')),
                ('illustrator', models.CharField(blank=True, max_length=255, null=True, verbose_name='일러스트레이터')),
                ('original', models.CharField(blank=True, max_length=255, null=True, verbose_name='원작 제목')),
                ('age_rating', models.CharField(max_length=20, verbose_name='연령 등급')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='가격')),
                ('url', models.URLField(verbose_name='작품 URL')),
                ('episode', models.IntegerField(blank=True, null=True, verbose_name='총 회차')),
                ('comments', models.IntegerField(blank=True, null=True, verbose_name='댓글 수')),
                ('recent_comments_count', models.IntegerField(blank=True, null=True, verbose_name='최근 댓글 수')),
                ('first_episode', models.DateField(blank=True, null=True, verbose_name='첫 연재일')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='인기도')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('basic_preference', models.TextField(blank=True, null=True)),
                ('romance_preference', models.TextField(blank=True, null=True)),
                ('rofan_preference', models.TextField(blank=True, null=True)),
                ('fantasy_preference', models.TextField(blank=True, null=True)),
                ('historical_preference', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedWork',
            fields=[
                ('recommended_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.BigIntegerField()),
                ('recommended_model', models.CharField(max_length=50)),
                ('recommended_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
