# Generated by Django 5.1.6 on 2025-03-20 10:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetContents',
            fields=[
                ('content_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='콘텐츠 ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('type', models.CharField(choices=[('웹툰', '웹툰'), ('웹소설', '웹소설')], max_length=20, verbose_name='타입')),
                ('platform', models.CharField(max_length=50, verbose_name='플랫폼')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('keywords', models.TextField(verbose_name='키워드')),
                ('synopsis', models.TextField(verbose_name='시놉시스')),
                ('thumbnail', models.URLField(verbose_name='썸네일 URL')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=30, verbose_name='닉네임')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('email', models.CharField(max_length=50, verbose_name='이메일')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('real_age', models.IntegerField(blank=True, verbose_name='만 나이')),
                ('gender', models.CharField(max_length=30, verbose_name='성별')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('persona_type', models.TextField(verbose_name='사용자 취향 설명')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
